### ISSUE TITLE
Option to disable animations?

### ISSUE THREAD

**Issue by jasonhendee** [tiberiuzuld/angular-gridster2#127]
Just as the title says.. would you be willing to build in a way to completely turn off all transitions/animations?

Thanks!

**Comment by tiberiuzuld** [comment]
Hi @jasonhendee ,

You need to override the css to disable the transitions. 
No need for an extra option.

Thanks,

**Comment by jasonhendee** [comment]
Ended up doing exactly that.  Thanks!

**Comment by tmtron** [comment]
This worked for me.

In the top-level `styles.css` I've added:

```css
gridster .gridster-column,
gridster .gridster-row,
gridster-item,
gridster-item.gridster-item-resizing,
gridster-item.gridster-item-moving {
  transition: unset !important;
}
```
