### ISSUE TITLE
Border colour for gridster items

### ISSUE THREAD

**Issue by xbotuk** [tiberiuzuld/angular-gridster2#252]
How can we define border colour for the gridster items?

**Comment by petarGitNik** [comment]
Just a notice, I'm not a contributor, just a user of this library, and this is how I add borders. Try targeting with CSS `<gridster-item>`. Or wrap an item in `<div>` and add CSS styles. For example:

```html
<gridster-item *ngFor="let item of dashboard" [item]="item">
    <div class="wrapper-for-border">
         <!-- your widget stuff -->
    </div>
</gridster-item>
```

And then:

```css
.wrapper-for-border {
    border: 1px solid black;
}
```

**Comment by tiberiuzuld** [comment]
Hi @xbotuk ,
Or just add:
```css
gridster-item {
 border: 1px solid black;
}
```
