### ISSUE TITLE
How to fill the margin lines between cells

### ISSUE THREAD

**Issue by shyambhiogade** [tiberiuzuld/angular-gridster2#366]
hi @tiberiuzuld , 
how to fill the lines between cells with different color, right now it just show the background color of grid.

**Comment by shyambhiogade** [comment]
@tiberiuzuld can you please reply if its possible easily. 
![gridstermargin](https://user-images.githubusercontent.com/10468130/41736589-d870f656-7541-11e8-9840-8376d7ca1a25.png)

**Comment by tiberiuzuld** [comment]
Hi @shyambhiogade ,
You can't at the moment, will consider adding this feature.

**Comment by admir86** [comment]
please add also a possibility to change the grid lines color. for now I can use `:host gridster /deep/ .gridster-column` but `deep` is deprecated.

https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

**Comment by tiberiuzuld** [comment]
That should work without `deep` since the grid is using `  encapsulation: ViewEncapsulation.None`

**Comment by admir86** [comment]
without `deep` it works only if the style definition is in the global css. but not if the style is defined in the css of my dashboard component.

**Comment by tiberiuzuld** [comment]
True, but I don't think is worth it to make an api for all the css values properties out there.
Those values should be changed from css not from JS api.
This initial issues is about the structure of how the grid lines are formed to enable to color the lines between widgets.
As a mater of fact got an idea on how do it from css without any change in the library.
hey @shyambhiogade ,
You can use this css to make your lines a different color
```css
gridster .gridster-column {
    border-left: 1px solid red;
    border-right: 1px solid red;
    outline: 10px solid red;
}
gridster .gridster-row {
    border-top: 1px solid red;
    border-bottom: 1px solid red;
    outline: 10px solid red;
}
```
![image](https://user-images.githubusercontent.com/15310395/49596318-ba368500-f982-11e8-85ee-81a43a8fdfd4.png)
