### ISSUE TITLE
How change color of a widget placeholder when moving with a widget.

### ISSUE THREAD

**Issue by xDavidK** [tiberiuzuld/angular-gridster2#490]
![grey_behind_widget](https://user-images.githubusercontent.com/49433604/55786038-c73fbe00-5ab3-11e9-8b35-cf1edcc2c20d.jpg)

**Comment by tiberiuzuld** [comment]
Hi @xDavidK ,
```css
gridster-preview.gridster-preview {
    background: red;
}
```
