### ISSUE TITLE
cannot change the styling of gridster-row and gridster-column

### ISSUE THREAD

**Issue by Andriusavlas** [tiberiuzuld/angular-gridster2#500]
How can I change the styling of gridster-row and gridster-column? tried these, none worked:
::ng-deep .gridster-row {
  border-top: 3px dashed green !important;
  border-bottom: 3px dashed green !important;
}

gridster .gridster-row {
  border-top: 3px dashed green !important;
  border-bottom: 3px dashed green !important;
}

Tried it both with, and without the !imporant, still nothing changes.

**Comment by tiberiuzuld** [comment]
Hi @Andriusavlas ,
I don't know what to say for me it works like this:
```css
gridster .gridster-row {
    border-top: 3px dashed green;
    border-bottom: 3px dashed green;
}
```
Be care full not to be inside `:host`. All of the components in library use `ViewEncapsulation.None` so it should work to override css easily.
